### ISSUE TITLE
Installation Guide

### ISSUE THREAD

**Issue by Messa1** [clayharmon/bb-lazy-load#1]
Hey there.

I just want to test you plugin i installed and activated it. But i cant see any change at the column or row settings. Can you explain where i need to make the changes set up background image lazy loaded.

Best regards

**Comment by clayharmon** [comment]
@Messa1 Hello! The plugin automatically lazy loads all background images for columns and rows, you may need to clear your beaver builder cache by going to Settings->Beaver Builder->Tools->Clear Cache.
