### ISSUE TITLE
Custom javascript breaks when activated

### ISSUE THREAD

**Issue by audpxi** [clayharmon/bb-lazy-load#15]
Hi!

Plugins seems great, but encountered error when activating plugin. We have some custom javascript on php template and it breaks when plugin is activated (custom javascript uses kind of same class than beaver builder).

DEV (plugin activated and settings on): http://sportspotdev2.paas.datacenter.fi/urheilupersoonat/
LIVE (plugin disabled): https://sportspot.fi/urheilupersoonat/

Our custom script builds row like this (bootstrap rows and columns):

`
        // Processes the gotten JSON data inti HTML string array
        function getHTMLStructure(sm) {
            var html;
            var s;
            if (sm.title == false) { sm.title = ""; }

            html = '<div class="person_card col-md-6 col-lg-3" data-url="' + sm.profile_url + '">';
                html += '<div class="person_container">';
                    html += '<div class="person_wrapper">';
                    html += '<a href="' + sm.profile_url + '" data-href="' + sm.profpic + '" class="progressive replace">';
                        html += '<img class="preview" src="https://sportspot.fi/wp-content/uploads/2019/01/placeholder.jpg" alt="' + sm.display_name + '" />';
                    html += '</a>';
                        html += '<div class="person_wrapper_inline">';
                            html += '<h3 class="person_name">' + sm.display_name + '</h3>';
                            html += '<p class="person_title">' + sm.title + '</p>';
                            html += '<a href="' + sm.profile_url + '" class="person_button">Tutustu</a>';
                            html += '<div class="add_to_catalog" data-user="' + sm.user_id + '"><i class="far fa-plus-square fa-lg"></i></div>';
                        html += '</div>';
                    html += '</div>';
                html += '</div>';
            html += '</div>';
           
            return html;
        }`

**Comment by audpxi** [comment]
This custom JavaScript is in custom beaver builder module. That's why it's trying to lazy load those images too. Maybe there could be setting to allow this only on beaver builder default modules, because the custom module is already using progressive image loading.

**Comment by audpxi** [comment]
Also bugnote here:
If you disable plugin --> all bg images shows only empty image. In every template and page. But if you disable images from settings first and then disable plugin -> all images works correctly.

**Comment by clayharmon** [comment]
@audpxi thank you. Will look into this soon. As for the bugnote - that is probably because the beaver builder cache needs to be cleared again to add back the background-image css. I will make it do this automatically in the future when the plugin is disabled.

**Comment by clayharmon** [comment]
@audpxi latest version should fix the Javascript issue and the bugnote you mentioned. #17
