### ISSUE TITLE
Media Library, SVGs, and content-slider

### ISSUE THREAD

**Issue by axraph** [clayharmon/bb-lazy-load#18]
Hello Clay! Thank you for the neat plugin! I'm trying to use it to handle all the webp and lazyloading for very long beaver builder pages. Just the perfect use case for the plugin :) I'm currently testing it and noticed few issues:

- Media library doesn't load correctly unless I disable the plugin, keeps loading but nothing shows, no errors in the inspector. This includes admin and builder editor pages.

- The plugin adds .webp to svg images. Is there a way to bypass svgs?

- The plugin handles the background images correctly for rows and columns, is there a way to include or support the background images created by the content-slider module?

Link to test website: https://test-path-bulletin.pantheonsite.io/issue-43/
Link to live (No BBLL there): https://path-bulletin.com/issue-43/

Thank you again 👍

**Comment by clayharmon** [comment]
@axraph I will jump on these soon, sorry for the late reply.

**Comment by clayharmon** [comment]
@axraph sorry for the lie above.. just now fixed this issue in 0.4.8
