### ISSUE TITLE
Undefined index: webp

### ISSUE THREAD

**Issue by trivendor** [clayharmon/bb-lazy-load#2]
Hi - thanks for the plugin.

In admin > settings > bb lazy load  I have Enable .webp? exampleimage.jpg.webp  unchecked

however a ton of PHP error notices are getting thrown (probably for every image on a page)

Undefined index: webp
wp-content/plugins/bb-lazy-load-master/bb-lazy-load.php:121
wp-content/plugins/bb-lazy-load-master/bb-lazy-load.php:144

with Enable .webp? exampleimage.jpg.webp  checked these notices don't get triggered

however I do get an error for 

Undefined index: image_html
wp-content/plugins/bb-lazy-load-master/bb-lazy-load.php:23

plugin is working to lazy load beaver builder row background images - which is pretty cool
--

**Comment by clayharmon** [comment]
@trivendor hello, I've released 0.3 which should fix this issue. Let me know if you have any more problems.

**Comment by trivendor** [comment]
Hi Clay -- new version caused a trainwreck

whole rows that use background images prevented from loading - and on another page the row displayed but without image

**Comment by clayharmon** [comment]
@trivendor are you getting any errors in the dev console or any php errors? Could you try clearing you beaver builder cache or click the save button on the settings page again to clear it

**Comment by trivendor** [comment]
Hi - 
the issue became pretty obvious

in settings I had enabled Enable .webp? exampleimage.jpg.webp

and it is appending the background image file name with webp

**Comment by clayharmon** [comment]
@trivendor if you uncheck the Enable .webp does everything work?

You'll need to use [EWWW Image Optimizer](https://wordpress.org/plugins/ewww-image-optimizer/) to generate .webp files, otherwise the images won't be found.

**Comment by trivendor** [comment]
yes - things work fine without enabling .webp? But...

Notice | Undefined index: image_html | 1 | +wp-content/plugins/bb-lazy-load-master/bb-lazy-load.php:23 | Plugin: bb-lazy-load-master

Notice | Undefined index: webp | 21 | +wp-content/plugins/bb-lazy-load-master/bb-lazy-load.php:121 | Plugin: bb-lazy-load-master

Notice | Undefined index: webp | 86 | +wp-content/plugins/bb-lazy-load-master/bb-lazy-load.php:144

**Comment by clayharmon** [comment]
@trivendor are you still getting undefined index notices with the latest version?

**Comment by trivendor** [comment]
Hi Clay -

fresh download and install
unchecked Enable .webp? exampleimage.jpg.webp
checked Enable lazy loading for column background images?
checked Enable lazy loading for row background images?
unchecked Enable lazy loading for row parallax images?
unchecked Enable lazy load for all Beaver Builder img tags? (Experimental)

Query Monitor shows PHP error warnings
huge number of errors on page with lots of different images and elements

another simpler page shows these

Warning | DOMDocument::loadHTML(): Unexpected end tag : p in Entity, line: 99 | 2 | +wp-content/plugins/bb-lazy-load-master/bb-lazy-load.php:133 | Plugin: bb-lazy-load-master
-- | -- | -- | -- | --
Warning | DOMDocument::loadHTML(): Unexpected end tag : p in Entity, line: 281 | 2 | +wp-content/plugins/bb-lazy-load-master/bb-lazy-load.php:133 | Plugin: bb-lazy-load-master
Warning | DOMDocument::loadHTML(): Tag svg invalid in Entity, line: 73 | 1 | +wp-content/plugins/bb-lazy-load-master/bb-lazy-load.php:133 | Plugin: bb-lazy-load-master
Warning | DOMDocument::loadHTML(): Tag path invalid in Entity, line: 73 | 1 | +wp-content/plugins/bb-lazy-load-master/bb-lazy-load.php:133 | Plugin: bb-lazy-load-master
Warning | DOMDocument::loadHTML(): Unexpected end tag : p in Entity, line: 378 | 1 | +wp-content/plugins/bb-lazy-load-master/bb-lazy-load.php:133 | Plugin: bb-lazy-load-master
Warning | DOMDocument::loadHTML(): Unexpected end tag : p in Entity, line: 1306 | 1 | +wp-content/plugins/bb-lazy-load-master/bb-lazy-load.php:133 | Plugin: bb-lazy-load-master


sorry but won't be able to test it further

Regards,

**Comment by clayharmon** [comment]
@trivendor those are simply warnings - not errors - from DOMDocument because the HTML it is parsing is not valid (HTML5 is not valid for DOMDocument). So the only thing I will be able to do is suppress those warnings. 

Is everything else working as intended?

**Comment by clayharmon** [comment]
@trivendor could you also tell me what PHP version you are using?

**Comment by trivendor** [comment]
PHP Version 7.2.17
WP Version 5.1.1
