### ISSUE TITLE
Disable lazy while page building

### ISSUE THREAD

**Issue by superfein** [clayharmon/bb-lazy-load#3]
Hi Clay thanks for this great plugin! 

I'm particularly interested in the IMG tag lazy load feature. Although it says Experimental, it seems to work well. The only issue I have is that while I'm building a page or post, the images disappear while I'm building. Clearly the lazy load functionality should be disabled during the build process, and then enabled when the page has been saved/published. 

Any chance of adding this feature in the near future?

**Comment by clayharmon** [comment]
@superfein thank you for that suggestion! I've published a release ([0.3.1](https://github.com/clayharmon/bb-lazy-load/releases/tag/v0.3.1)) that has that fix.

**Comment by superfein** [comment]
Thanks Clay, really appreciate all your hard work on this. Such a useful and necessary plugin.
