### ISSUE TITLE
Images don't load in iOS mobile browsers

### ISSUE THREAD

**Issue by superfein** [clayharmon/bb-lazy-load#4]
The images do not load in Safari or Chrome mobile in iOS. Seems to be a bug. I've included a screenshot of the issue on my mobile device (iPhone 5s). 

The strange white text that looks garbled, those are supposed to be images. They load fine in Chrome's mobile emulator, seems to be an actual issue with the mobile browsers.

![image1](https://user-images.githubusercontent.com/10688655/55034276-2379fb00-503b-11e9-812f-e98bd6485198.png)

**Comment by clayharmon** [comment]
@superfein I've pushed an update that uses https://github.com/verlok/lazyload for the javascript instead of my own for better browser compatibility. Please backup before updating to be safe, let me know if you have any issues.
